### PR TITLE
Update view/mxGraph

### PR DESCRIPTION
**Pull request by hungtcs**

### CODE REVIEW

**Comment by tbouffard** [comment]
:+1: nice, tough work!

**Comment by hungtcs** [comment]
Hi @tbouffard,  I got a lot of errors when building my project after update, please do not update your project to avoid inconvenience, I will check it later tomorrow

**Comment by hungtcs** [comment]
Good night!

**Comment by hungtcs** [comment]
@tbouffard fixed in 6680ea19ff4e3780633e107d7c9b995574bda1bd, my project is now running perfectly.

**Comment by tbouffard** [comment]
cool thanks.

**Pull request merged**
