### PR TITLE
Fix typescript strict check errors

### LINKED ISSUE #14: Ensure definitions respect 'noImplicitAny'
Some elements defined in the lib version `1.0.2` currently do not respect that
When use in a project with tsconfig `noImplicitAny` set to `true`, this generates some TypeScript errors like
- node_modules/mxgraph-type-definitions/handler/mxKeyHandler.d.ts(14,31): error TS7006: Parameter 'target' implicitly has an 'any' type
- node_modules/mxgraph-type-definitions/shape/mxStencil.d.ts(140,3): error TS7010: 'drawChildren', which lacks return-type annotation, implicitly has an 'any' return type.

**Workaround**: set `skipLibCheck` to `true`

### PR DESCRIPTION
**Pull request by tbouffard**
Fix TypeScript compilation errors.
To ensure no new compilation errors are introduced, setup a GitHub workflow that check this on Pull Request and master branch.

closes #14

### CODE REVIEW

**Comment by tbouffard** [comment]
@hungtcs the worklow is currently not triggered. Can you check if the repository settings allow running actions from 3rd party please?
This should work as described in https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-events-for-forked-repositories

**Comment by hungtcs** [comment]
Hi @tbouffard, the pull request not trigger workflow may be because the repository currently does not have a workflow, it only exists in the pull request, I created a test worklow, it will be trigger in the next pull request if nothing went wrong

**Comment by tbouffard** [comment]
> Hi @tbouffard, the pull request not trigger workflow may be because the repository currently does not have a workflow, it only exists in the pull request, I created a test worklow, it will be trigger in the next pull request if nothing went wrong

@hungtcs you were totally right, I gave it a try by merging master into this PR branch, and the blank workflow and the newly introduce worklflow have been run.
- blank wf: https://github.com/hungtcs/mxgraph-type-definitions/pull/15/checks?check_run_id=821569593 : fail as expected
- new build wf: https://github.com/hungtcs/mxgraph-type-definitions/pull/15/checks?check_run_id=821569537
I am going to rebase the PR on the latest master

**Comment by tbouffard** [comment]
@hungtcs I have pushed all commits related to the contribution I wanted to do.
Feel free to review it.
Thanks again for helping me with the GitHub Workflow so quickly, it was great (as always) :smile_cat:

**Comment by hungtcs** [comment]
Thank you, @tbouffard

**Pull request merged**
